name: food_travel
description: Food and travel discovery app with trip planning
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  mapbox_maps_flutter: ^2.2.0
  geolocator: ^11.0.0
  intl: ^0.19.0
  collection: ^1.18.0
  shared_preferences: ^2.2.2
  uuid: ^4.4.0

  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geocoding: ^4.0.0
  url_launcher: ^6.3.2
  crypto: ^3.0.3

  # ==== Thêm cho đăng ký/đăng nhập bằng Email + Mật khẩu ====
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  # ==========================================================

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
